#!/usr/bin/env python3
"""Paper bundle helper, run by tools/paper-bundle.sh.

  bundle.py cited                 write the paper's \\code{} tokens
  bundle.py emit OUT              assemble the self-contained bundle
  bundle.py tokens BUNDLE         check every \\code{} token occurs in BUNDLE

The bundle is the source text, verbatim, of every declaration listed in
.lake/paper-bundle/closure.tsv, in import order with the namespace, section
and open commands around it, followed by Paper/Statements.lean below its
imports. Rust modules come last, before the Rust statements.
"""
import collections, os, re, sys

DIR = '.lake/paper-bundle'
TEX = 'paper/molt.tex'
PROSE = {'typewriter', 'xxx', 'thm_xxx', 'MoltPaper.xxx'}  # \\code{} used in running text, not a name
NOT_LEAN = re.compile(r'[/ ]|^\d|^#|\.lean$|\.ts$|\.rs$')

def tokens():
    tex = open(TEX).read()
    toks = re.findall(r'\\code\{([^}]*)\}', tex[tex.index('\\begin{document}'):])
    toks = [t.replace('\\_', '_').replace("$'$", "'") for t in toks]
    return sorted({t for t in toks if not NOT_LEAN.search(t) and t not in PROSE})

def path(m): return m.replace('.', '/') + '.lean'

def order(mods):
    deps = {}
    def imports(m):
        if m in deps: return
        deps[m] = [x for x in re.findall(r'(?m)^import\s+(\S+)', open(path(m)).read())
                   if os.path.exists(path(x))]
        for d in deps[m]: imports(d)
    for m in mods: imports(m)
    out, seen = [], set()
    def visit(m):
        if m in seen: return
        seen.add(m)
        for d in deps[m]: visit(d)
        out.append(m)
    for m in sorted(deps): visit(m)
    return out

STRUCT = re.compile(r'(namespace|end|section|noncomputable section|open|set_option|universe)\b')

def module_text(m, ranges):
    lines = open(path(m)).read().split('\n')
    keep = set()
    for a, b in ranges: keep.update(range(a, b + 1))
    out, comment, prev = [], 0, False
    for i, l in enumerate(lines, 1):
        if i in keep:
            if not prev: out.append('')
            out.append(l); prev = True; continue
        prev = False
        if comment:
            comment += l.count('/-') - l.count('-/'); continue
        if l.startswith('/-'):
            comment = l.count('/-') - l.count('-/'); continue
        if l.rstrip().endswith(' in'):
            # `open … in` scopes over the declaration right after it
            if i + 1 in keep: out.append(''); out.append(l); prev = True
            continue
        if STRUCT.match(l):
            # the Thales runtime stub is empty; nothing in it is reachable
            if l.strip() == 'open Thales.TS': continue
            out.append(l)
    text = '\n' + '\n'.join(out) + '\n'
    for _ in range(4):
        text = re.sub(r'\n(?:noncomputable )?section\n((?:open|set_option)[^\n]*\n|\n)*end\n', '\n', text)
        text = re.sub(r'\n(?:noncomputable )?section (\S+)\n((?:open|set_option)[^\n]*\n|\n)*end \1\n', '\n', text)
        text = re.sub(r'\nnamespace (\S+)\n((?:open|set_option)[^\n]*\n|\n)*end \1\n', '\n', text)
    return f'\n/-! ### `{m}` -/\n' + re.sub(r'\n{3,}', '\n\n', text)

HEADER = '''/-
Molt Petit: the paper's definitions and theorem statements, self-contained.
Lean 4 ({toolchain}) with Mathlib and Aeneas. GENERATED by
tools/paper-bundle.sh from the development; do not edit.

Given: the development compiles, contains no `sorry`, and proves each
`MoltPaper.thm_xxx` below as `theorem MoltPaper.xxx : MoltPaper.thm_xxx`,
using no axioms beyond `propext`, `Classical.choice` and `Quot.sound`.
The paper cites each result by its name `xxx`. The development's gate also
checks that every declaration here elaborates to the same term as there.

The definitions are the development's source text, verbatim, in dependency
order; the code extracted from the Rust implementation (Charon + Aeneas)
comes last, before the statements about it.
-/
import Mathlib
import Aeneas

set_option linter.all false
'''

def emit(out):
    R = collections.defaultdict(list)
    for l in open(f'{DIR}/closure.tsv'):
        m, a, b, _ = l.rstrip('\n').split('\t')
        R[m].append((int(a), int(b)))
    mods = order(list(R))
    st = open('Paper/Statements.lean').read()
    st = st[st.index('/-!'):]
    cut = st.index('/-! ## The Rust implementation -/')
    tc = open('lean-toolchain').read().strip()
    parts = [HEADER.format(toolchain=tc), '\n/-! # Part I. Definitions -/']
    parts += [module_text(m, sorted(R[m])) for m in mods if m in R and not m.startswith('Rust.')]
    parts += ['\n/-! # Part II. Statements -/\n', st[:cut] + 'end MoltPaper\n',
              '\n/-! # Part III. The Rust implementation, as extracted -/']
    parts += [module_text(m, sorted(R[m])) for m in mods if m in R and m.startswith('Rust.')]
    parts += ['\n/-! # Part IV. Statements about the Rust implementation -/\n',
              'set_option linter.unusedVariables false\n\nnamespace MoltPaper\n\n' + st[cut:]]
    text = re.sub(r'\n{3,}', '\n\n', '\n'.join(parts))
    open(out, 'w').write(text)

def check_tokens(bundle):
    text = open(bundle).read()
    missing = [t for t in tokens() if not re.search(r'(?<![\w.])(?:thm_)?' + re.escape(t.split('.')[-1]) + r'(?![\w\'?!])', text)]
    for t in missing: print(f'paper cites `{t}`, which the bundle does not contain', file=sys.stderr)
    return not missing

if __name__ == '__main__':
    cmd = sys.argv[1]
    if cmd == 'cited':
        os.makedirs(DIR, exist_ok=True)
        open(f'{DIR}/cited.txt', 'w').write('\n'.join(tokens()) + '\n')
    elif cmd == 'emit': emit(sys.argv[2])
    elif cmd == 'tokens': sys.exit(0 if check_tokens(sys.argv[2]) else 1)
