/-
VENDORED FILE — emitted by Charon + Aeneas (https://github.com/AeneasVerif)
from the Rust crate at `rust/` (crate `molt_petit`, `rust/src/lib.rs`):

    charon cargo --preset=aeneas        # rust/  ->  molt_petit.llbc
    aeneas molt_petit.llbc -backend lean -dest …   # -> MoltPetit.lean

Regenerate with `rust/extract.sh`. This is the Rust analogue of the
Thales-emitted `Spec/TS.lean`: the protocol is written in the Rust
fragment Charon+Aeneas translate to Lean, and the theorems in
`Rust/Properties.lean` are about exactly these emitted definitions.

The Rust avoids `==` on `Option` and explicit `Box::as_ref` so the
extraction is axiom-free (no opaque `axiom` declarations); `#print axioms`
on the proofs returns only Lean's three classical axioms.
-/
-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [molt_petit]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace molt_petit

/-- [molt_petit::Hash]
    Source: 'src/lib.rs', lines 31:0-36:1
    Visibility: public -/
structure Hash where
  a : Std.U64
  b : Std.U64
  c : Std.U64
  d : Std.U64

/-- [molt_petit::{impl core::clone::Clone for molt_petit::Hash}::clone]:
    Source: 'src/lib.rs', lines 30:9-30:14
    Visibility: public -/
def Hash.Insts.CoreCloneClone.clone (self : Hash) : Result Hash := do
  ok self

/-- Trait implementation: [molt_petit::{impl core::clone::Clone for molt_petit::Hash}]
    Source: 'src/lib.rs', lines 30:9-30:14 -/
@[reducible]
def Hash.Insts.CoreCloneClone : core.clone.Clone Hash := {
  clone := Hash.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [molt_petit::{impl core::marker::Copy for molt_petit::Hash}]
    Source: 'src/lib.rs', lines 30:16-30:20 -/
@[reducible]
def Hash.Insts.CoreMarkerCopy : core.marker.Copy Hash := {
  cloneInst := Hash.Insts.CoreCloneClone
}

/-- [molt_petit::hash_eq]:
    Source: 'src/lib.rs', lines 39:0-41:1
    Visibility: public -/
def hash_eq (x : Hash) (y : Hash) : Result Bool := do
  if x.a = y.a
  then
    if x.b = y.b
    then if x.c = y.c
         then ok (x.d = y.d)
         else ok false
    else ok false
  else ok false

/-- [molt_petit::Block]
    Source: 'src/lib.rs', lines 49:0-60:1
    Visibility: public -/
structure Block where
  slot : Std.U64
  height : Std.U64
  prev : Option Hash
  id : Hash
  contents_hash : Hash
  key_index : Std.U64

/-- [molt_petit::Chain]
    Source: 'src/lib.rs', lines 63:0-66:1
    Visibility: public -/
@[discriminant isize]
inductive Chain where
| Nil : Chain
| Cons : Block → Chain → Chain

/-- [molt_petit::quorum]:
    Source: 'src/lib.rs', lines 75:0-77:1
    Visibility: public -/
def quorum (n : Std.U64) : Result Std.U64 := do
  let i ← n + n
  let i1 ← i + 2#u64
  i1 / 3#u64

/-- [molt_petit::max_byzantine]:
    Source: 'src/lib.rs', lines 80:0-82:1
    Visibility: public -/
def max_byzantine (n : Std.U64) : Result Std.U64 := do
  let i ← n - 1#u64
  i / 3#u64

/-- [molt_petit::producer_for_slot]:
    Source: 'src/lib.rs', lines 85:0-87:1
    Visibility: public -/
def producer_for_slot (n : Std.U64) (slot : Std.U64) : Result Std.U64 := do
  slot % n

/-- [molt_petit::is_nil]:
    Source: 'src/lib.rs', lines 93:0-98:1
    Visibility: public -/
def is_nil (c : Chain) : Result Bool := do
  match c with
  | Chain.Nil => ok true
  | Chain.Cons _ _ => ok false

/-- [molt_petit::tip_slot_from]:
    Source: 'src/lib.rs', lines 101:0-106:1
    Visibility: public -/
def tip_slot_from (cur : Std.U64) (c : Chain) : Result Std.U64 := do
  match c with
  | Chain.Nil => ok cur
  | Chain.Cons b tl => tip_slot_from b.slot tl
partial_fixpoint

/-- [molt_petit::tip_height_from]:
    Source: 'src/lib.rs', lines 109:0-114:1
    Visibility: public -/
def tip_height_from (cur : Std.U64) (c : Chain) : Result Std.U64 := do
  match c with
  | Chain.Nil => ok cur
  | Chain.Cons b tl => tip_height_from b.height tl
partial_fixpoint

/-- [molt_petit::tip_id_from]:
    Source: 'src/lib.rs', lines 117:0-122:1
    Visibility: public -/
def tip_id_from (cur : Hash) (c : Chain) : Result Hash := do
  match c with
  | Chain.Nil => ok cur
  | Chain.Cons b tl => tip_id_from b.id tl
partial_fixpoint

/-- [molt_petit::append_block]:
    Source: 'src/lib.rs', lines 125:0-130:1
    Visibility: public -/
def append_block (c : Chain) (nb : Block) : Result Chain := do
  match c with
  | Chain.Nil => ok (Chain.Cons nb Chain.Nil)
  | Chain.Cons x tl => let c1 ← append_block tl nb
                       ok (Chain.Cons x c1)
partial_fixpoint

/-- [molt_petit::window_count]:
    Source: 'src/lib.rs', lines 133:0-141:1
    Visibility: public -/
def window_count
  (c : Chain) (u : Std.U64) (len : Std.U64) : Result Std.U64 := do
  match c with
  | Chain.Nil => ok 0#u64
  | Chain.Cons b tl =>
    let here ←
      if u <= b.slot
      then do
           let i ← u + len
           if b.slot < i
           then ok 1#u64
           else ok 0#u64
      else ok 0#u64
    let i ← window_count tl u len
    here + i
partial_fixpoint

/-- [molt_petit::window_dense]:
    Source: 'src/lib.rs', lines 144:0-146:1
    Visibility: public -/
def window_dense (n : Std.U64) (c : Chain) (u : Std.U64) : Result Bool := do
  let i ← quorum n
  let i1 ← window_count c u n
  ok (i <= i1)

/-- [molt_petit::anchors_dense]:
    Source: 'src/lib.rs', lines 154:0-167:1
    Visibility: public -/
def anchors_dense
  (all : Chain) (rest : Chain) (lo : Std.U64) (t : Std.U64) (n : Std.U64) :
  Result Bool
  := do
  match rest with
  | Chain.Nil => ok true
  | Chain.Cons b tl =>
    let u ← b.slot + 1#u64
    let ok1 ←
      if lo <= u
      then
        do
        let i ← u + n
        let i1 ← t + 1#u64
        if i <= i1
        then window_dense n all u
        else ok true
      else ok true
    if ok1
    then anchors_dense all tl lo t n
    else ok false
partial_fixpoint

/-- [molt_petit::matured_dense]:
    Source: 'src/lib.rs', lines 170:0-177:1
    Visibility: public -/
def matured_dense
  (c : Chain) (lo : Std.U64) (t : Std.U64) (n : Std.U64) : Result Bool := do
  let i ← lo + n
  let i1 ← t + 1#u64
  let base ← if i <= i1
               then window_dense n c lo
               else ok true
  if base
  then anchors_dense c c lo t n
  else ok false

/-- [molt_petit::genesis_ok]:
    Source: 'src/lib.rs', lines 184:0-186:1
    Visibility: public -/
def genesis_ok (b : Block) : Result Bool := do
  if b.height = 0#u64
  then ok (core.option.Option.is_none b.prev)
  else ok false

/-- [molt_petit::child_ok]:
    Source: 'src/lib.rs', lines 190:0-196:1
    Visibility: public -/
def child_ok (parent : Block) (child : Block) : Result Bool := do
  let (parent1, prev_ok) ←
    match child.prev with
    | none => ok (parent, false)
    | some p => do
                let prev_ok1 ← hash_eq p parent.id
                ok (parent, prev_ok1)
  let i ← parent1.height + 1#u64
  if child.height = i
  then if parent1.slot < child.slot
       then ok prev_ok
       else ok false
  else ok false

/-- [molt_petit::links_from]:
    Source: 'src/lib.rs', lines 199:0-204:1 -/
def links_from (parent : Block) (c : Chain) : Result Bool := do
  match c with
  | Chain.Nil => ok true
  | Chain.Cons b tl =>
    let b1 ← child_ok parent b
    if b1
    then links_from b tl
    else ok false
partial_fixpoint

/-- [molt_petit::links_ok]:
    Source: 'src/lib.rs', lines 207:0-212:1
    Visibility: public -/
def links_ok (c : Chain) : Result Bool := do
  match c with
  | Chain.Nil => ok true
  | Chain.Cons a tl => links_from a tl

/-- [molt_petit::valid_chain]:
    Source: 'src/lib.rs', lines 216:0-226:1
    Visibility: public -/
def valid_chain (n : Std.U64) (c : Chain) : Result Bool := do
  match c with
  | Chain.Nil => ok true
  | Chain.Cons g tl =>
    let genesis ← genesis_ok g
    let links ← links_ok c
    let tip_slot ← tip_slot_from g.slot tl
    if genesis
    then if links
         then matured_dense c 0#u64 tip_slot n
         else ok false
    else ok false

/-- [molt_petit::key_mono_against]:
    Source: 'src/lib.rs', lines 247:0-259:1 -/
def key_mono_against
  (n : Std.U64) (slot : Std.U64) (ki : Std.U64) (rest : Chain) :
  Result Bool
  := do
  match rest with
  | Chain.Nil => ok true
  | Chain.Cons b tl =>
    let i ← producer_for_slot n slot
    let i1 ← producer_for_slot n b.slot
    let ok1 ← if i = i1
                then ok (ki <= b.key_index)
                else ok true
    if ok1
    then key_mono_against n slot ki tl
    else ok false
partial_fixpoint

/-- [molt_petit::key_mono_ok]:
    Source: 'src/lib.rs', lines 268:0-273:1
    Visibility: public -/
def key_mono_ok (n : Std.U64) (c : Chain) : Result Bool := do
  match c with
  | Chain.Nil => ok true
  | Chain.Cons b tl =>
    let b1 ← key_mono_against n b.slot b.key_index tl
    if b1
    then key_mono_ok n tl
    else ok false
partial_fixpoint

/-- [molt_petit::valid_chain_k]:
    Source: 'src/lib.rs', lines 278:0-280:1
    Visibility: public -/
def valid_chain_k (n : Std.U64) (c : Chain) : Result Bool := do
  let b ← valid_chain n c
  if b
  then key_mono_ok n c
  else ok false

/-- [molt_petit::produce_block]:
    Source: 'src/lib.rs', lines 289:0-320:1
    Visibility: public -/
def produce_block
  (n : Std.U64) (me : Std.U64) (at_slot : Std.U64) (new_id : Hash)
  (contents_hash : Hash) (key_index : Std.U64) (c : Chain) :
  Result (Option Chain)
  := do
  let i ← producer_for_slot n at_slot
  if i != me
  then ok none
  else
    let b ← is_nil c
    if b
    then ok none
    else
      let th ← tip_height_from 0#u64 c
      let ti ← tip_id_from new_id c
      let i1 ← th + 1#u64
      let extended ←
        append_block c
          {
            slot := at_slot,
            height := i1,
            prev := (some ti),
            id := new_id,
            contents_hash,
            key_index
          }
      let b1 ← valid_chain n extended
      if b1
      then ok (some extended)
      else ok none

/-- [molt_petit::CertClaim]
    Source: 'src/lib.rs', lines 328:0-333:1
    Visibility: public -/
structure CertClaim where
  tip_slot : Std.U64
  tip_height : Std.U64
  tip_id : Hash
  tail : Chain

/-- [molt_petit::SignedChain]
    Source: 'src/lib.rs', lines 336:0-339:1
    Visibility: public -/
@[discriminant isize]
inductive SignedChain where
| SNil : SignedChain
| SCons : Block → Hash → SignedChain → SignedChain

/-- [molt_petit::CertifiedChain]
    Source: 'src/lib.rs', lines 343:0-346:1
    Visibility: public -/
@[discriminant isize]
inductive CertifiedChain where
| Invalid : CertifiedChain
| CC : Hash → SignedChain → CertifiedChain

/-- Trait declaration: [molt_petit::Crypto]
    Source: 'src/lib.rs', lines 351:0-363:1
    Visibility: public -/
structure Crypto (Self : Type) where
  verify : Self → Hash → Block → Hash → Result Bool
  key_for : Self → Std.U64 → Std.U64 → Result Hash
  sign : Self → Hash → Block → Result Hash
  cert_verify : Self → Hash → Result Bool
  cert_claim : Self → Hash → Result CertClaim

/-- [molt_petit::strip_sigs]:
    Source: 'src/lib.rs', lines 366:0-381:1
    Visibility: public -/
def strip_sigs (sc : SignedChain) : Result Chain := do
  match sc with
  | SignedChain.SNil => ok Chain.Nil
  | SignedChain.SCons b _ tl => let c ← strip_sigs tl
                                ok (Chain.Cons b c)
partial_fixpoint

/-- [molt_petit::sigs_ok]:
    Source: 'src/lib.rs', lines 384:0-392:1
    Visibility: public -/
def sigs_ok
  {C : Type} (CryptoInst : Crypto C) (n : Std.U64) (crypto : C)
  (sc : SignedChain) :
  Result Bool
  := do
  match sc with
  | SignedChain.SNil => ok true
  | SignedChain.SCons b sig tl =>
    let i ← producer_for_slot n b.slot
    let key ← CryptoInst.key_for crypto i b.key_index
    let b1 ← CryptoInst.verify crypto key b sig
    if b1
    then sigs_ok CryptoInst n crypto tl
    else ok false
partial_fixpoint

/-- [molt_petit::links_to_claim]:
    Source: 'src/lib.rs', lines 400:0-406:1 -/
def links_to_claim (cl : CertClaim) (s1 : Block) : Result Bool := do
  let (cl1, prev_ok) ←
    match s1.prev with
    | none => ok (cl, false)
    | some p => do
                let prev_ok1 ← hash_eq p cl.tip_id
                ok (cl, prev_ok1)
  let i ← cl1.tip_height + 1#u64
  if s1.height = i
  then if cl1.tip_slot < s1.slot
       then ok prev_ok
       else ok false
  else ok false

/-- [molt_petit::suffix_lo]:
    Source: 'src/lib.rs', lines 412:0-418:1 -/
def suffix_lo (n : Std.U64) (tip_slot : Std.U64) : Result Std.U64 := do
  let i ← tip_slot + 2#u64
  if n > i
  then ok 0#u64
  else i - n

/-- [molt_petit::clone_chain]:
    Source: 'src/lib.rs', lines 453:0-468:1 -/
def clone_chain (c : Chain) : Result Chain := do
  match c with
  | Chain.Nil => ok Chain.Nil
  | Chain.Cons b tl => let c1 ← clone_chain tl
                       ok (Chain.Cons b c1)
partial_fixpoint

/-- [molt_petit::append_suffix_to_buffer]:
    Source: 'src/lib.rs', lines 436:0-451:1 -/
def append_suffix_to_buffer
  (buffer : Chain) (suffix : Chain) : Result Chain := do
  match buffer with
  | Chain.Nil => clone_chain suffix
  | Chain.Cons b tl =>
    let c ← append_suffix_to_buffer tl suffix
    ok (Chain.Cons b c)
partial_fixpoint

/-- [molt_petit::validate_suffix]:
    Source: 'src/lib.rs', lines 420:0-433:1
    Visibility: public -/
def validate_suffix
  (n : Std.U64) (cl : CertClaim) (suffix : Chain) : Result Bool := do
  match suffix with
  | Chain.Nil => ok true
  | Chain.Cons s1 tl =>
    let link ← links_to_claim cl s1
    let links ← links_from s1 tl
    let tip_slot ← tip_slot_from s1.slot tl
    let buf ← append_suffix_to_buffer cl.tail suffix
    let lo ← suffix_lo n cl.tip_slot
    if link
    then if links
         then matured_dense buf lo tip_slot n
         else ok false
    else ok false

/-- [molt_petit::FloorList]
    Source: 'src/lib.rs', lines 478:0-481:1
    Visibility: public -/
@[discriminant isize]
inductive FloorList where
| FNil : FloorList
| FCons : Std.U64 → Std.U64 → FloorList → FloorList

/-- [molt_petit::floor_lookup]:
    Source: 'src/lib.rs', lines 485:0-496:1
    Visibility: public -/
def floor_lookup (fl : FloorList) (i : Std.U64) : Result Std.U64 := do
  match fl with
  | FloorList.FNil => ok 0#u64
  | FloorList.FCons p f tl => if p = i
                              then ok f
                              else floor_lookup tl i
partial_fixpoint

/-- [molt_petit::clone_floors]:
    Source: 'src/lib.rs', lines 498:0-503:1 -/
def clone_floors (fl : FloorList) : Result FloorList := do
  match fl with
  | FloorList.FNil => ok FloorList.FNil
  | FloorList.FCons p f tl =>
    let fl1 ← clone_floors tl
    ok (FloorList.FCons p f fl1)
partial_fixpoint

/-- [molt_petit::floor_bump]:
    Source: 'src/lib.rs', lines 507:0-528:1
    Visibility: public -/
def floor_bump
  (fl : FloorList) (i : Std.U64) (v : Std.U64) : Result FloorList := do
  match fl with
  | FloorList.FNil => ok FloorList.FNil
  | FloorList.FCons p f tl =>
    let nf ← if p = i
               then if f < v
                    then ok v
                    else ok f
               else ok f
    let rest ← if p = i
                 then clone_floors tl
                 else floor_bump tl i v
    ok (FloorList.FCons p nf rest)
partial_fixpoint

/-- [molt_petit::floors_shape_from]:
    Source: 'src/lib.rs', lines 534:0-539:1 -/
def floors_shape_from
  (i : Std.U64) (n : Std.U64) (fl : FloorList) : Result Bool := do
  match fl with
  | FloorList.FNil => ok (i = n)
  | FloorList.FCons p _ tl =>
    if p = i
    then
      if i < n
      then let i1 ← i + 1#u64
           floors_shape_from i1 n tl
      else ok false
    else ok false
partial_fixpoint

/-- [molt_petit::floors_shape_ok]:
    Source: 'src/lib.rs', lines 543:0-545:1
    Visibility: public -/
def floors_shape_ok (n : Std.U64) (fl : FloorList) : Result Bool := do
  floors_shape_from 0#u64 n fl

/-- [molt_petit::key_mono_from]:
    Source: 'src/lib.rs', lines 550:0-560:1
    Visibility: public -/
def key_mono_from
  (n : Std.U64) (fl : FloorList) (c : Chain) : Result Bool := do
  match c with
  | Chain.Nil => ok true
  | Chain.Cons b tl =>
    let i ← producer_for_slot n b.slot
    let i1 ← floor_lookup fl i
    let bumped ← floor_bump fl i b.key_index
    if i1 <= b.key_index
    then key_mono_from n bumped tl
    else ok false
partial_fixpoint

/-- [molt_petit::validate_suffix_k]:
    Source: 'src/lib.rs', lines 565:0-567:1
    Visibility: public -/
def validate_suffix_k
  (n : Std.U64) (cl : CertClaim) (fl : FloorList) (suffix : Chain) :
  Result Bool
  := do
  let b ← validate_suffix n cl suffix
  if b
  then
    let b1 ← floors_shape_ok n fl
    if b1
    then key_mono_from n fl suffix
    else ok false
  else ok false

/-- [molt_petit::validate_certified_chain]:
    Source: 'src/lib.rs', lines 572:0-581:1
    Visibility: public -/
def validate_certified_chain
  {C : Type} (CryptoInst : Crypto C) (n : Std.U64) (crypto : C)
  (cc : CertifiedChain) :
  Result Bool
  := do
  match cc with
  | CertifiedChain.Invalid => ok false
  | CertifiedChain.CC cert suffix =>
    let cl ← CryptoInst.cert_claim crypto cert
    let stripped ← strip_sigs suffix
    let b ← CryptoInst.cert_verify crypto cert
    if b
    then
      let b1 ← sigs_ok CryptoInst n crypto suffix
      if b1
      then validate_suffix n cl stripped
      else ok false
    else ok false

/-- [molt_petit::signed_tip_height_from]:
    Source: 'src/lib.rs', lines 584:0-589:1 -/
def signed_tip_height_from
  (cur : Std.U64) (sc : SignedChain) : Result Std.U64 := do
  match sc with
  | SignedChain.SNil => ok cur
  | SignedChain.SCons b _ tl => signed_tip_height_from b.height tl
partial_fixpoint

/-- [molt_petit::signed_tip_id_from]:
    Source: 'src/lib.rs', lines 591:0-596:1 -/
def signed_tip_id_from (cur : Hash) (sc : SignedChain) : Result Hash := do
  match sc with
  | SignedChain.SNil => ok cur
  | SignedChain.SCons b _ tl => signed_tip_id_from b.id tl
partial_fixpoint

/-- [molt_petit::append_signed]:
    Source: 'src/lib.rs', lines 599:0-606:1 -/
def append_signed
  (sc : SignedChain) (nb : Block) (sig : Hash) : Result SignedChain := do
  match sc with
  | SignedChain.SNil => ok (SignedChain.SCons nb sig SignedChain.SNil)
  | SignedChain.SCons b s tl =>
    let sc1 ← append_signed tl nb sig
    ok (SignedChain.SCons b s sc1)
partial_fixpoint

/-- [molt_petit::produce_block_cert]:
    Source: 'src/lib.rs', lines 612:0-646:1
    Visibility: public -/
def produce_block_cert
  {C : Type} (CryptoInst : Crypto C) (n : Std.U64) (me : Std.U64)
  (at_slot : Std.U64) (new_id : Hash) (contents_hash : Hash)
  (key_index : Std.U64) (sk : Hash) (crypto : C) (cert : Hash)
  (suffix : SignedChain) :
  Result CertifiedChain
  := do
  let i ← producer_for_slot n at_slot
  if i != me
  then ok CertifiedChain.Invalid
  else
    let cl ← CryptoInst.cert_claim crypto cert
    let tip_h ← signed_tip_height_from cl.tip_height suffix
    let tip_i ← signed_tip_id_from cl.tip_id suffix
    let i1 ← tip_h + 1#u64
    let sig ←
      CryptoInst.sign crypto sk
        {
          slot := at_slot,
          height := i1,
          prev := (some tip_i),
          id := new_id,
          contents_hash,
          key_index
        }
    let new_suffix ←
      append_signed suffix
        {
          slot := at_slot,
          height := i1,
          prev := (some tip_i),
          id := new_id,
          contents_hash,
          key_index
        } sig
    let b ←
      validate_certified_chain CryptoInst n crypto (CertifiedChain.CC cert
        new_suffix)
    if b
    then ok (CertifiedChain.CC cert new_suffix)
    else ok CertifiedChain.Invalid

/-- Trait declaration: [molt_petit::Backend]
    Source: 'src/lib.rs', lines 662:0-675:1
    Visibility: public -/
structure Backend (Self : Type) (Self_Num : Type) (Self_Bool : Type) where
  coremarkerCopyInst : core.marker.Copy Self_Num
  zero : Self → Result Self_Num
  one : Self → Result Self_Num
  add : Self → Self_Num → Self_Num → Result Self_Num
  lt : Self → Self_Num → Self_Num → Result Self_Bool
  eq : Self → Self_Num → Self_Num → Result Self_Bool
  and : Self → Self_Bool → Self_Bool → Result Self_Bool
  or : Self → Self_Bool → Self_Bool → Result Self_Bool
  not : Self → Self_Bool → Result Self_Bool
  bool_const : Self → Bool → Result Self_Bool
  bool_to_num : Self → Self_Bool → Result Self_Num

/-- [molt_petit::U64Backend]
    Source: 'src/lib.rs', lines 678:0-678:22
    Visibility: public -/
@[reducible]
def U64Backend := Unit

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::bool_to_num]:
    Source: 'src/lib.rs', lines 692:4-692:67
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.bool_to_num
  (self : U64Backend) (b : Bool) : Result Std.U64 := do
  if b
  then ok 1#u64
  else ok 0#u64

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::bool_const]:
    Source: 'src/lib.rs', lines 691:4-691:47
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.bool_const
  (self : U64Backend) (b : Bool) : Result Bool := do
  ok b

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::not]:
    Source: 'src/lib.rs', lines 690:4-690:41
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.not
  (self : U64Backend) (a : Bool) : Result Bool := do
  ok (¬ a)

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::or]:
    Source: 'src/lib.rs', lines 689:4-689:53
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.or
  (self : U64Backend) (a : Bool) (b : Bool) : Result Bool := do
  if a
  then ok true
  else ok b

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::and]:
    Source: 'src/lib.rs', lines 688:4-688:54
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.and
  (self : U64Backend) (a : Bool) (b : Bool) : Result Bool := do
  if a
  then ok b
  else ok false

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::eq]:
    Source: 'src/lib.rs', lines 687:4-687:51
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.eq
  (self : U64Backend) (a : Std.U64) (b : Std.U64) : Result Bool := do
  ok (a = b)

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::lt]:
    Source: 'src/lib.rs', lines 686:4-686:50
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.lt
  (self : U64Backend) (a : Std.U64) (b : Std.U64) : Result Bool := do
  ok (a < b)

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::add]:
    Source: 'src/lib.rs', lines 685:4-685:50
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.add
  (self : U64Backend) (a : Std.U64) (b : Std.U64) : Result Std.U64 := do
  a + b

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::one]:
    Source: 'src/lib.rs', lines 684:4-684:30
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.one
  (self : U64Backend) : Result Std.U64 := do
  ok 1#u64

/-- [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}::zero]:
    Source: 'src/lib.rs', lines 683:4-683:31
    Visibility: public -/
def U64Backend.Insts.Molt_petitBackendU64Bool.zero
  (self : U64Backend) : Result Std.U64 := do
  ok 0#u64

/-- Trait implementation: [molt_petit::{impl molt_petit::Backend<u64, bool> for molt_petit::U64Backend}]
    Source: 'src/lib.rs', lines 680:0-693:1 -/
@[reducible]
def U64Backend.Insts.Molt_petitBackendU64Bool : Backend U64Backend Std.U64 Bool
  := {
  coremarkerCopyInst := core.marker.CopyU64
  zero := U64Backend.Insts.Molt_petitBackendU64Bool.zero
  one := U64Backend.Insts.Molt_petitBackendU64Bool.one
  add := U64Backend.Insts.Molt_petitBackendU64Bool.add
  lt := U64Backend.Insts.Molt_petitBackendU64Bool.lt
  eq := U64Backend.Insts.Molt_petitBackendU64Bool.eq
  and := U64Backend.Insts.Molt_petitBackendU64Bool.and
  or := U64Backend.Insts.Molt_petitBackendU64Bool.or
  not := U64Backend.Insts.Molt_petitBackendU64Bool.not
  bool_const := U64Backend.Insts.Molt_petitBackendU64Bool.bool_const
  bool_to_num := U64Backend.Insts.Molt_petitBackendU64Bool.bool_to_num
}

/-- [molt_petit::HashG]
    Source: 'src/lib.rs', lines 696:0-701:1
    Visibility: public -/
structure HashG (N : Type) where
  a : N
  b : N
  c : N
  d : N

/-- [molt_petit::BlockG]
    Source: 'src/lib.rs', lines 705:0-711:1
    Visibility: public -/
structure BlockG (N : Type) where
  slot : N
  height : N
  has_prev : Bool
  prev : HashG N
  id : HashG N

/-- [molt_petit::ChainG]
    Source: 'src/lib.rs', lines 714:0-717:1
    Visibility: public -/
@[discriminant isize]
inductive ChainG (N : Type) where
| NilG : ChainG N
| ConsG : BlockG N → ChainG N → ChainG N

/-- [molt_petit::hashg_eq]:
    Source: 'src/lib.rs', lines 720:0-728:1 -/
def hashg_eq
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (x : HashG Clause0_Num)
  (y : HashG Clause0_Num) :
  Result Clause0_Bool
  := do
  let ea ← BackendInst.eq be x.a y.a
  let eb ← BackendInst.eq be x.b y.b
  let ec ← BackendInst.eq be x.c y.c
  let ed ← BackendInst.eq be x.d y.d
  let eab ← BackendInst.and be ea eb
  let ecd ← BackendInst.and be ec ed
  BackendInst.and be eab ecd

/-- [molt_petit::window_count_be]:
    Source: 'src/lib.rs', lines 731:0-745:1 -/
def window_count_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (c : ChainG Clause0_Num)
  (u : Clause0_Num) (len : Clause0_Num) :
  Result Clause0_Num
  := do
  match c with
  | ChainG.NilG => BackendInst.zero be
  | ChainG.ConsG b tl =>
    let lt_lo ← BackendInst.lt be b.slot u
    let ge_u ← BackendInst.not be lt_lo
    let hi ← BackendInst.add be u len
    let lt_hi ← BackendInst.lt be b.slot hi
    let inw ← BackendInst.and be ge_u lt_hi
    let here ← BackendInst.bool_to_num be inw
    let rest ← window_count_be BackendInst be tl u len
    BackendInst.add be here rest
partial_fixpoint

/-- [molt_petit::window_dense_be]:
    Source: 'src/lib.rs', lines 748:0-752:1 -/
def window_dense_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (q : Clause0_Num)
  (c : ChainG Clause0_Num) (u : Clause0_Num) (n : Clause0_Num) :
  Result Clause0_Bool
  := do
  let cnt ← window_count_be BackendInst be c u n
  let lt ← BackendInst.lt be cnt q
  BackendInst.not be lt

/-- [molt_petit::genesis_ok_be]:
    Source: 'src/lib.rs', lines 755:0-760:1 -/
def genesis_ok_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (b : BlockG Clause0_Num) :
  Result Clause0_Bool
  := do
  let t ← BackendInst.zero be
  let h0 ← BackendInst.eq be b.height t
  let has ← BackendInst.bool_const be b.has_prev
  let np ← BackendInst.not be has
  BackendInst.and be h0 np

/-- [molt_petit::child_ok_be]:
    Source: 'src/lib.rs', lines 763:0-772:1 -/
def child_ok_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (parent : BlockG Clause0_Num)
  (child : BlockG Clause0_Num) :
  Result Clause0_Bool
  := do
  let t ← BackendInst.one be
  let succ ← BackendInst.add be parent.height t
  let h_ok ← BackendInst.eq be child.height succ
  let slot_ok ← BackendInst.lt be parent.slot child.slot
  let prev_eq ← hashg_eq BackendInst be child.prev parent.id
  let has ← BackendInst.bool_const be child.has_prev
  let prev_ok ← BackendInst.and be has prev_eq
  let hs ← BackendInst.and be h_ok slot_ok
  BackendInst.and be hs prev_ok

/-- [molt_petit::links_from_be]:
    Source: 'src/lib.rs', lines 775:0-784:1 -/
def links_from_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (parent : BlockG Clause0_Num)
  (c : ChainG Clause0_Num) :
  Result Clause0_Bool
  := do
  match c with
  | ChainG.NilG => BackendInst.bool_const be true
  | ChainG.ConsG b tl =>
    let here ← child_ok_be BackendInst be parent b
    let rest ← links_from_be BackendInst be b tl
    BackendInst.and be here rest
partial_fixpoint

/-- [molt_petit::links_ok_be]:
    Source: 'src/lib.rs', lines 787:0-792:1 -/
def links_ok_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (c : ChainG Clause0_Num) :
  Result Clause0_Bool
  := do
  match c with
  | ChainG.NilG => BackendInst.bool_const be true
  | ChainG.ConsG a tl => links_from_be BackendInst be a tl

/-- [molt_petit::tip_slot_from_be]:
    Source: 'src/lib.rs', lines 795:0-800:1 -/
def tip_slot_from_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (cur : Clause0_Num)
  (c : ChainG Clause0_Num) :
  Result Clause0_Num
  := do
  match c with
  | ChainG.NilG => ok cur
  | ChainG.ConsG b tl => tip_slot_from_be BackendInst be b.slot tl
partial_fixpoint

/-- [molt_petit::anchors_dense_be]:
    Source: 'src/lib.rs', lines 803:0-830:1 -/
def anchors_dense_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (all : ChainG Clause0_Num)
  (rest : ChainG Clause0_Num) (lo : Clause0_Num) (t : Clause0_Num)
  (n : Clause0_Num) (q : Clause0_Num) :
  Result Clause0_Bool
  := do
  match rest with
  | ChainG.NilG => BackendInst.bool_const be true
  | ChainG.ConsG b tl =>
    let t1 ← BackendInst.one be
    let u ← BackendInst.add be b.slot t1
    let lt_u_lo ← BackendInst.lt be u lo
    let lo_le_u ← BackendInst.not be lt_u_lo
    let u_plus_n ← BackendInst.add be u n
    let t11 ← BackendInst.add be t t1
    let lt_t1 ← BackendInst.lt be t11 u_plus_n
    let matured ← BackendInst.not be lt_t1
    let cond ← BackendInst.and be lo_le_u matured
    let dense ← window_dense_be BackendInst be q all u n
    let ncond ← BackendInst.not be cond
    let ok1 ← BackendInst.or be ncond dense
    let rest_ok ← anchors_dense_be BackendInst be all tl lo t n q
    BackendInst.and be ok1 rest_ok
partial_fixpoint

/-- [molt_petit::matured_dense_be]:
    Source: 'src/lib.rs', lines 833:0-850:1 -/
def matured_dense_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (c : ChainG Clause0_Num)
  (lo : Clause0_Num) (t : Clause0_Num) (n : Clause0_Num) (q : Clause0_Num) :
  Result Clause0_Bool
  := do
  let lo_plus_n ← BackendInst.add be lo n
  let t1 ← BackendInst.one be
  let t11 ← BackendInst.add be t t1
  let lt_base ← BackendInst.lt be t11 lo_plus_n
  let base_matured ← BackendInst.not be lt_base
  let dense_lo ← window_dense_be BackendInst be q c lo n
  let nbase ← BackendInst.not be base_matured
  let base ← BackendInst.or be nbase dense_lo
  let anch ← anchors_dense_be BackendInst be c c lo t n q
  BackendInst.and be base anch

/-- [molt_petit::valid_chain_be]:
    Source: 'src/lib.rs', lines 854:0-866:1
    Visibility: public -/
def valid_chain_be
  {B : Type} {Clause0_Num : Type} {Clause0_Bool : Type} (BackendInst : Backend
  B Clause0_Num Clause0_Bool) (be : B) (n : Clause0_Num) (q : Clause0_Num)
  (c : ChainG Clause0_Num) :
  Result Clause0_Bool
  := do
  match c with
  | ChainG.NilG => BackendInst.bool_const be true
  | ChainG.ConsG g tl =>
    let genesis ← genesis_ok_be BackendInst be g
    let links ← links_ok_be BackendInst be c
    let tip ← tip_slot_from_be BackendInst be g.slot tl
    let t ← BackendInst.zero be
    let dense ← matured_dense_be BackendInst be c t tip n q
    let gl ← BackendInst.and be genesis links
    BackendInst.and be gl dense

end molt_petit
